// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbl0trHR6MiojT0g--SlWYQLn-W3yEhG0',
    appId: '1:1081699625484:web:eee9565dc9aae4b9d25c29',
    messagingSenderId: '1081699625484',
    projectId: 'hello-6cdbb',
    authDomain: 'hello-6cdbb.firebaseapp.com',
    storageBucket: 'hello-6cdbb.firebasestorage.app',
    measurementId: 'G-9KEN9QS2ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvKIl43OCTmN4mubW72gotEIFPGGSmed8',
    appId: '1:1081699625484:android:5f9044bab00535bdd25c29',
    messagingSenderId: '1081699625484',
    projectId: 'hello-6cdbb',
    storageBucket: 'hello-6cdbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa-J5La9ZbSoSf1D4z80BcqksN765s6a8',
    appId: '1:1081699625484:ios:3fa2ddbee618812ad25c29',
    messagingSenderId: '1081699625484',
    projectId: 'hello-6cdbb',
    storageBucket: 'hello-6cdbb.firebasestorage.app',
    iosBundleId: 'com.example.hello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa-J5La9ZbSoSf1D4z80BcqksN765s6a8',
    appId: '1:1081699625484:ios:3fa2ddbee618812ad25c29',
    messagingSenderId: '1081699625484',
    projectId: 'hello-6cdbb',
    storageBucket: 'hello-6cdbb.firebasestorage.app',
    iosBundleId: 'com.example.hello',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbl0trHR6MiojT0g--SlWYQLn-W3yEhG0',
    appId: '1:1081699625484:web:d1a2530f8fe63ddcd25c29',
    messagingSenderId: '1081699625484',
    projectId: 'hello-6cdbb',
    authDomain: 'hello-6cdbb.firebaseapp.com',
    storageBucket: 'hello-6cdbb.firebasestorage.app',
    measurementId: 'G-FT0S58NDGL',
  );
}
